name: global_apps

services:
  global_mysql:
    image: mysql:8.0
    container_name: global_mysql
    env_file:
      - .env/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "10.50.0.1:3306:3306"

  globalapp_nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: globalapp_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt

volumes:
  mysql_data:
  nginx_data:
  nginx_letsencrypt:
