name: global_apps
services:
  global_portainer:
    image: portainer/portainer-ce:latest
    container_name: global_portainer
    restart: unless-stopped
    expose:
      - "8000"
      - "9443"
    ports:
      - "10.50.0.1:102:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: