name: global_apps

services:
  global_mysql:
    image: mysql:8.0
    container_name: global_mysql
    env_file:
      - .env/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "10.50.0.1:3306:3306"

  globalapp_nginxPM:
    image: jc21/nginx-proxy-manager:latest
    container_name: globalapp_nginxPM
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx_pm_data:/data
      - nginx_pm_letsencrypt:/etc/letsencrypt

volumes:
  mysql_data :
    external: true
    name: global_apps_mysql_data
  nginx_pm_data:
    external: true
    name: global_apps_nginx_pm_data
  nginx_pm_letsencrypt:
    external: true
    name: global_apps_nginx_pm_letsencrypt